local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
  s("makefile", {
    t("NAME := "), i(1, "<name>"), t({"", ""}),

    t("SRC := "), i(2, "<sources>"), t({"", ""}),
	t({
		"SRC_DIR := src/",
	  "SRC := $(addprefix $(SRC_DIR), $(SRC))",
      "",
      "OBJ := $(SRC:.cpp=.o)",
	  "OBJ_DIR := obj/",
	  "OBJ := $(patsubst $(SRC_DIR)%.cpp, $(OBJ_DIR)%.o, $SRC)",
      "",
      "DEP := $(SRC:.cpp=.d)",
      "",
      "###",
      "",
      "CXX := c++",
      "",
	  "CXXSTD := std=c++11",
      "",
      "CXXFLAGS := -Wall -Wextra -Werror $(CXXSTD)",
      "",
      "DFLAGS := -MMD -MP",
      "",
      "###",
      "",
      "all: $(NAME)",
      "",
      "$(NAME): $(OBJ)",
      "\t$(CXX) $(CFLAGS) $(OBJ) -o $@",
	  "",
	  "debug: $(CXXFLAGS) += -g",
	  "debug: all",
      "",
      "$(OBJ_DIR)%.o: $(SRC_DIR)%.cpp",
	  "\tmkdir -p $(dir $@)",
      "\t$(CXX) $(CFLAGS) $(DFLAGS) $(STD) $< -c -o $@",
      "",
      "-include $(DEP)",
      "",
      "clean:",
      "\trm -rf $(OBJ) $(DEP)",
      "",
      "fclean: clean",
      "\trm -rf $(NAME)",
      "",
      "re: fclean all",
      "",
      ".PHONY: all debug clean fclean re",
    }),
}),
}
